---
version: "2"
run:
  go: "1.25"
  build-tags:
    - small
    - medium
    - large
linters:
  enable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - errchkjson
    - errcheck
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocritic
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - iface
    - importas
    - intrange
    - interfacebloat
    - ireturn
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - whitespace
    - wrapcheck
    - wsl_v5

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 12
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
    sloglint:
      no-raw-keys: true
      no-mixed-args: false
      kv-only: true
      no-global: "all"
    wsl_v5:
      disable:
        - if
        - expr
        - append
        - range
        - assign
        - decl
        - return
        - defer
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - wsl_v5
          - revive
          - exhaustruct
          - wrapcheck
          - goconst
          - gochecknoglobals
formatters:
  enable:
    - gofmt
    - goimports
